---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .name }}
          env:
          {{- range $key, $value := .vars}}
          - name: '{{ $key }}'
            value: '{{ $value }}'
          {{- end}}
