---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .name }}
          resources:
            limits:
              memory: {{ .limits.memory }}
              cpu: {{ .limits.cpu }}