apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .name }}
  ports:
  - name: http
    port: {{ .containerPort }}
    protocol: TCP
    targetPort: {{ .containerPort }}
